apiVersion: v1
appVersion: 2.0.1
description: |
  Eclipse Ditto™ is a technology in the IoT implementing a software pattern called “digital twins”.
  A digital twin is a virtual, cloud based, representation of his real world counterpart
  (real world “Things”, e.g. devices like sensors, smart heating, connected cars, smart grids, EV charging stations etc).
home: https://www.eclipse.org/ditto
icon: https://www.eclipse.org/ditto/images/ditto.svg
keywords:
- iot-chart
- IoT
maintainers:
- email: axel.koehler@kiwigrid.com
  name: axdotl
- email: thomas.jaeckle@bosch.io
  name: thjaeckle
- email: stefan.maute@bosch.io
  name: stmaute
name: ditto
sources:
- https://github.com/eclipse/ditto
- https://github.com/eclipse/packages
version: 2.0.1
