@proto = http
@hostname = 141.19.44.65 
@user = ditto
@honodevice = yumi
@org = abb
@honotenant = abb
@honodevicepwd = sehrgeheim
@manufacturer = abb
@pwd = ditto
@port = 38443
@httpadapterport = 18443
@devregport = 28443
@dittoport = 38443
@dittodevopsusr = devops
@dittodevopspwd = foo

########################################################################################
### Create Tenant ######################################################################
########################################################################################

curl -i -X POST http://{{hostname}}:{{devregport}}/v1/tenants/{{honotenant}}

###

curl -i -X POST http://{{hostname}}:{{devregport}}/v1/tenants/hallo

########################################################################################
### Register Device ####################################################################
########################################################################################

curl -i -X POST http://{{hostname}}:{{devregport}}/v1/devices/{{honotenant}}/{{org}}:{{honodevice}}

########################################################################################
### Set Device Credentials #############################################################
########################################################################################

curl -i -X PUT -H "Content-Type: application/json" --data '[
{
  "type": "hashed-password",
  "auth-id": "{{honodevice}}",
  "secrets": [{
    "pwd-plain": "{{honodevicepwd}}"
  }]
}]' http://{{hostname}}:{{devregport}}/v1/credentials/{{honotenant}}/{{org}}:{{honodevice}}

########################################################################################
### Create Connection ##################################################################
########################################################################################

curl -i -X POST -u devops:foobar -H 'Content-Type: application/json' --data '{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:createConnection",
    "connection": {
      "id": "hono-connection-for-'"abb"'",
      "connectionType": "amqp-10",
      "connectionStatus": "open",
      "uri": "amqp://consumer%40HONO:verysecret@'"c2e"'-dispatch-router-ext:15672",
      "failoverEnabled": true,
      "sources": [
        {
          "addresses": [
            "telemetry/'"abb"'",
            "event/'"abb"'"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "enforcement": {
            "input": "{{ header:device_id }}",
            "filters": [
              "{{ entity:id }}"
            ]
          },
          "headerMapping": {
            "hono-device-id": "{{ header:device_id }}",
            "content-type": "{{ header:content-type }}"
          },
          "replyTarget": {
            "enabled": true,
            "address": "{{ header:reply-to }}",
            "headerMapping": {
              "to": "command/'"abb"'/{{ header:hono-device-id }}",
              "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
              "correlation-id": "{{ header:correlation-id }}",
              "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}"
            },
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          },
          "acknowledgementRequests": {
            "includes": [],
            "filter": "fn:filter(header:qos,'"'"'ne'"'"','"'"'0'"'"')"
          }
        },
        {
          "addresses": [
            "command_response/'"abb"'/replies"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "headerMapping": {
            "content-type": "{{ header:content-type }}",
            "correlation-id": "{{ header:correlation-id }}",
            "status": "{{ header:status }}"
          },
          "replyTarget": {
            "enabled": false,
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          }
        }
      ],
      "targets": [
        {
          "address": "command/'"abb"'",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/live/commands",
            "_/_/things/live/messages"
          ],
          "headerMapping": {
            "to": "command/'"abb"'/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}",
            "reply-to": "{{ fn:default('"'"'command_response/'"abb"'/replies'"'"') | fn:filter(header:response-required,'"'"'ne'"'"','"'"'false'"'"') }}"
          }
        },
        {
          "address": "command/'"abb"'",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/twin/events",
            "_/_/things/live/events"
          ],
          "headerMapping": {
            "to": "command/'"abb"'/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}"
          }
        }
      ]
      
    }
  }
}' http://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity

###

\nfunction mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonData = JSON.parse(textPayload);const value = {measurements: {properties: {di_Stop: jsonData[\"metrics\"][\"di_Stop\"],OperatingMode: jsonData[\"metrics\"][\"OperatingMode\"]}}}; return Ditto.buildDittoProtocolMsg(abb,yumi,things,twin,commands,modify,/features,headers,value); }",


,
      "mappingDefinition": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {     const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));const jsonData = JSON.parse(textPayload);const value = {measurements: {properties: {OperatingMode: 25}}};return Ditto.buildDittoProtocolMsg('abb','yumi','things','twin','commands','modify','/features',headers,value);}",
                    "loadBytebufferJS": "false",
                    "loadLongJS": "false"
                }
        }

########################################################################################
### Delete Connection ##################################################################
########################################################################################

POST {{proto}}://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity
Content-Type: application/json
Authorization: Basic {{dittodevopsusr}}:{{dittodevopspwd}}

{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:deleteConnection",
    "connectionId": "hono-connection-for-abb"
  }
}

########################################################################################
### Setup policy #######################################################################
########################################################################################

curl -i -X PUT -u ditto:ditto -H 'Content-Type: application/json' --data '{
  "entries": {
    "DEFAULT": {
      "subjects": {
        "{{ request:subjectId }}": {
           "type": "Ditto user authenticated via nginx"
        }
      },
      "resources": {
        "thing:/": {
          "grant": ["READ", "WRITE"],
          "revoke": []
        },
        "policy:/": {
          "grant": ["READ", "WRITE"],
          "revoke": []
        },
        "message:/": {
          "grant": ["READ", "WRITE"],
          "revoke": []
        }
      }
    },
    "HONO": {
      "subjects": {
        "pre-authenticated:hono-connection": {
          "type": "Connection to Eclipse Hono"
        }
      },
      "resources": {
        "thing:/": {
          "grant": ["READ", "WRITE"],
          "revoke": []
        },
        "message:/": {
          "grant": ["READ", "WRITE"],
          "revoke": []
        }
      }
    }
  }
}' http://{{hostname}}:{{dittoport}}/api/2/policies/{{org}}:{{honodevice}}

########################################################################################
### Create a twin ######################################################################
########################################################################################

curl -X PUT -u ditto:ditto -H 'Content-Type: application/json' --data '{
  "policyId": "{{org}}:{{honodevice}}",
  "attributes": {
    "location": "Mannheim",
    "manufacturer": "ABB",
    "roboter": "YuMi",
    "plc": "IRC5",
    "serial number": "4711"
  },
  "features": {
  }
}' http://{{hostname}}:{{dittoport}}/api/2/things/{{org}}:{{honodevice}}

########################################################################################
### DELETE THE TWIN ####################################################################
########################################################################################

DELETE {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/abb:yumi
Authorization: Basic ditto:ditto

########################################################################################
### Delete all Features #ä##############################################################
########################################################################################

DELETE {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/abb:yumi/features
Authorization: Basic ditto:ditto

########################################################################################
### New Features #ä#####################################################################
########################################################################################

PUT {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/abb:yumi/features
Content-Type: application/json
Authorization: Basic ditto:ditto

{
	"measurements": {
            "properties": {
                "di_Stop": true,
                "OperatingMode": "1"
            }
        }
}

########################################################################################
### PUBLISH TELEMETRY TO HONO ##########################################################
### Device and Tenant have to be provisioned previously ################################
########################################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}

########################################################################################
### PUBLISH TELEMETRY TO HONO ##########################################################
### Device and Tenant have to be provisioned previously ################################
########################################################################################

### NULL ###############################################################################
### Altitude ###########################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/altitude/value",
  "value": null
}

### Speed ##############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/speed/value",
  "value": null
}

### Heading #############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/heading/value",
  "value": null
}

### Bank ###############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/bank/value",
  "value": null
}

### INFLIGHT ###########################################################################
### Altitude ###########################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic nsp@joel:{{honodevicepwd}}

{
  "topic": "org.fournier/nsp/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/altitude/value",
  "value": 3000
}

### Speed ##############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/speed/value",
  "value": 185
}

### Heading #############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/heading/value",
  "value": 245
}

### Bank ###############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/bank/value",
  "value": 15
}



##### MQTT:

{
  "topic": "org.fournier/rf4/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}




########################################################################################
### Create Connection ##################################################################
########################################################################################

curl -i -X POST -u devops:foobar -H 'Content-Type: application/json' --data '{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:createConnection",
    "connection": {
      "id": "hono-connection-for-joel",
      "connectionType": "amqp-10",
      "connectionStatus": "open",
      "uri": "amqp://consumer%40HONO:verysecret@c2e-dispatch-router-ext:15672",
      "failoverEnabled": true,
      "sources": [
        {
          "addresses": [
            "telemetry/joel",
            "event/joel"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "enforcement": {
            "input": "{{ header:device_id }}",
            "filters": [
              "{{ entity:id }}"
            ]
          },
          "headerMapping": {
            "hono-device-id": "{{ header:device_id }}",
            "content-type": "{{ header:content-type }}"
          },
          "replyTarget": {
            "enabled": true,
            "address": "{{ header:reply-to }}",
            "headerMapping": {
              "to": "command/joel/{{ header:hono-device-id }}",
              "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
              "correlation-id": "{{ header:correlation-id }}",
              "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}"
            },
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          },
          "acknowledgementRequests": {
            "includes": [],
            "filter": "fn:filter(header:qos,'"'"'ne'"'"','"'"'0'"'"')"
          }
        },
        {
          "addresses": [
            "command_response/joel/replies"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "headerMapping": {
            "content-type": "{{ header:content-type }}",
            "correlation-id": "{{ header:correlation-id }}",
            "status": "{{ header:status }}"
          },
          "replyTarget": {
            "enabled": false,
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          }
        }
      ],
      "targets": [
        {
          "address": "command/joel",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/live/commands",
            "_/_/things/live/messages"
          ],
          "headerMapping": {
            "to": "command/joel/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}",
            "reply-to": "{{ fn:default('"'"'command_response/joel/replies'"'"') | fn:filter(header:response-required,'"'"'ne'"'"','"'"'false'"'"') }}"
          }
        },
        {
          "address": "command/joel",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/twin/events",
            "_/_/things/live/events"
          ],
          "headerMapping": {
            "to": "command/joel/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}"
          }
        }
      ]
    }
  }
}' http://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity




### DELETE Connection
POST http://devops:foobar@{{hostname}}:38443/devops/piggyback/connectivity?timeout=10 
Content-Type: application/json

{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:deleteConnection",
    "connectionId": "mqtt-example-connection"
  }
}


########################################################################################
### PUBLISH TELEMETRY TO HONO ##########################################################
### Device and Tenant have to be provisioned previously ################################
########################################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic nsp@joel:{{honodevicepwd}}

{
  "topic": "org.fournier/rf4/things/twin/commands/modify",
  "headers": {},
  "path": "/features/engine/properties/status/JoelTemp/value",
  "value": 999
}


###
{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}

###################

curl -i -X POST -u devops:foobar -H 'Content-Type: application/json' --data '{
{
      "targetActorSelection": "/system/sharding/connection",
      "headers": {
        "aggregate": false
      },
      "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
          "id": "hono-connection-for-joel",
          "connectionType": "amqp-10",
          "connectionStatus": "open",
          "uri": "amqp://consumer%40HONO:verysecret@c2e-dispatch-router-ext:15672",
          "failoverEnabled": true,
          "sources": [
            {
              "addresses": [
                "telemetry/joel",
                "event/joel"
              ],
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "enforcement": {
                "input": "{{ header:device_id }}",
                "filters": [
                  "{{ entity:id }}"
                ]
              },
              "headerMapping": {
                "hono-device-id": "{{ header:device_id }}",
                "content-type": "{{ header:content-type }}"
              },
              "replyTarget": {
                "enabled": true,
                "address": "{{ header:reply-to }}",
                "headerMapping": {
                  "to": "command/joel/{{ header:hono-device-id }}",
                  "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
                  "correlation-id": "{{ header:correlation-id }}",
                  "content-type": "{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}"
                },
                "expectedResponseTypes": [
                  "response",
                  "error"
                ]
              },
              "acknowledgementRequests": {
                "includes": [],
                "filter": "fn:filter(header:qos,'ne','0')"
              }
            },
            {
              "addresses": [
                "command_response/joel/replies"
              ],
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "headerMapping": {
                "content-type": "{{ header:content-type }}",
                "correlation-id": "{{ header:correlation-id }}",
                "status": "{{ header:status }}"
              },
              "replyTarget": {
                "enabled": false,
                "expectedResponseTypes": [
                  "response",
                  "error"
                ]
              }
            }
          ],
          "targets": [
            {
              "address": "command/joel",
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "topics": [
                "_/_/things/live/commands",
                "_/_/things/live/messages"
              ],
              "headerMapping": {
                "to": "command/joel/{{ thing:id }}",
                "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
                "content-type": "{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}",
                "correlation-id": "{{ header:correlation-id }}",
                "reply-to": "{{ fn:default('command_response/joel/replies') | fn:filter(header:response-required,'ne','false') }}"
              }
            },
            {
              "address": "command/joel",
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/events"
              ],
              "headerMapping": {
                "to": "command/joel/{{ thing:id }}",
                "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
                "content-type": "{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}",
                "correlation-id": "{{ header:correlation-id }}"
              }
            }
          ]
        }
      }
    }' http://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity


####

POST http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/backlightOn?timeout=0
Content-Type: x-correlation-id: command-and-control
Authorization: Basic ditto:ditto

{
  
}

####

POST http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/backlightOff?timeout=0
Content-Type: x-correlation-id: command-and-control
Authorization: Basic ditto:ditto

{
  
}

####


    curl -i -X POST 'http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/brew?timeout=0' \
     -u ditto:ditto \
     -H 'x-correlation-id: command-and-control' \
     -d '{"targetTemperature":85}'



#####

curl -i -X POST -u ditto:ditto -H 'Content-Type: application/json' -w '\n' --data '{
    "topic": "lehmann/smartDTsensor/things/live/messages/ask",
    "headers": {
        "content-type": "text/plain",
        "correlation-id": "a-unique-string-for-this-message"
    },
    "path": "/inbox/messages/ask",
    "value": "Hey, how are you?"
}' http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/turnoff?timeout=0


####


GET http://jreichwald.de:1880/settings
Authorization: Basic admin:admin1234

{
  
}

#### Test login scheme

GET http://jreichwald.de:1880/auth/login

### login

curl -X POST http://jreichwald.de:1880/auth/token --data 'client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=admin1234'

### login


POST http://twinserver.kve.hs-mannheim.de:18443/auth/token 
Content-Type: application/x-www-form-urlencoded

client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=admin1234


#Content-Type: client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=admin1234

### Token

@NodeRedToken = JUSZpHtMzNnVoa0j9AhlOGwxCEcxx0vFyF/ZunzurXvfsNL9B/Sd9qdY5cz66FreJPei8/f4p2L1CozdD20mLzG7UEGWVvJV/oduvWC7QZBZPRQCvmCW6d+AMQQb/tGoB/wn4E3oaLCNT/tWgN2qi9/igCVGcOs1458IK9hUVJU=

###

GET http://jreichwald.de:1880/settings
Authorization: Bearer {{NodeRedToken}}

####

PUT http://twinserver.kve.hs-mannheim.de:18443/flow/a1cabdb9.dfa9b
Authorization: Bearer {{NodeRedToken}}
Content-Type: application/json
Node-RED-Deployment-Type: reload

{
  "id": "a1cabdb9.dfa9b",
  "label": "Flow 1",
  "nodes": [ 
  {
        "id": "jo9aa7f7.8b39b8",
        "type": "inject",
        "z": "a1cabdb9.dfa9b",
        "repeat": "10",
        "payloadType": "date",
        "x": 130,
        "y": 80,
        "wires": [
            [
                "jof970af.305cf8"
            ]
        ]
    },
    {
        "id": "jof970af.305cf8",
        "type": "http request",
        "z": "a1cabdb9.dfa9b",
        "method": "GET",
        "url": "http://ditto:ditto@twinserver.kve.hs-mannheim.de:38443/api/2/things/selfy:smsensor/features/telemetry/properties/JoelTemp/value",
        "x": 330,
        "y": 80,
        "wires": [
            [
                "jodf7460.349a"
            ]
        ]
    },
    {
        "id": "jodf7460.349a",
        "type": "rbe",
        "z": "a1cabdb9.dfa9b",
        "func": "deadband",
        "gap": "1",
        "inout": "out",
        "property": "payload",
        "x": 530,
        "y": 80
    }
  ]
}


###PUT .../flow/:8f85aefb.b740d8

curl -X POST http://twinserver.kve.hs-mannheim.de:18443/flows -H 'content-type: application/json' -H "Authorization: Bearer {{NodeRedToken}}" -d '{
  "id": "8f85aefb.b740d8",
  "label": "Flow 1",
  "nodes": [ 
  {
        "id": "jo9aa7f7.8b39b8",
        "type": "inject",
        "z": "8f85aefb.b740d8",
        "repeat": "10",
        "payloadType": "date",
        "x": 130,
        "y": 80,
        "wires": [
            [
                "jof970af.305cf8"
            ]
        ]
    },
    {
        "id": "jof970af.305cf8",
        "type": "http request",
        "z": "8f85aefb.b740d8",
        "method": "GET",
        "url": "http://ditto:ditto@twinserver.kve.hs-mannheim.de:38443/api/2/things/selfy:smsensor/features/telemetry/properties/JoelTemp/value",
        "x": 330,
        "y": 80,
        "wires": [
            [
                "jodf7460.349a"
            ]
        ]
    },
    {
        "id": "jodf7460.349a",
        "type": "rbe",
        "z": "8f85aefb.b740d8",
        "func": "deadband",
        "gap": "1",
        "inout": "out",
        "property": "payload",
        "x": 530,
        "y": 80
    }
  ]
}
'


#####################################################################################

curl -X GET http://twinserver.kve.hs-mannheim.de:18443/flows -H 'content-type: application/json' -H "Authorization: Bearer {{NodeRedToken}}"
