@proto = http
@hostname = 141.19.44.61
@user = ditto
@honodevice = A320
@honotenant = airbus
@org = airb
@honodevicepwd = flugzeug
@pwd = ditto
@port = 30080 

@dittoport = 30080 
@dittodevopsusr = devops
@dittodevopspwd = foobar


########################################################################################
########################################################################################
### DITTO STUFF ########################################################################
########################################################################################
########################################################################################

########################################################################################
### Create Thing #######################################################################
########################################################################################

PUT {{proto}}://{{hostname}}:{{port}}/api/2/things/cemos:optmeasurementdev1
Content-Type: application/json
Authorization: Basic {{user}}:{{pwd}}

{
  "thingId": "cemos:optmeasurementdev1",
  "definition": "cemos:optmeasurementdev:0.1",
  "attributes": {
    "manufacturer": "ACME demo corp.",
    "location": "Mannheim University of Applied Sciences",
    "institute": "Center for Mass Spectrometry and Optical Spectroscopy",
    "serialno": "1",
    "model": "Optical Measurement Device"
  },
  "features": {
    "coffee-brewer": {
      "definition": [
        "com.acme:coffeebrewer:0.1.0"
      ],
      "properties": {
        "brewed-coffees": 0
      }
    },
    "water-tank": {
      "properties": {
        "configuration": {
          "smartMode": true,
          "brewingTemp": 87,
          "tempToHold": 44,
          "timeoutSeconds": 6000
        },
        "status": {
          "waterAmount": 731,
          "temperature": 44
        }
      }
    }
  }
}

########################################################################################
### Create MQTT Connection zu Julians Broker ###########################################
########################################################################################

POST {{proto}}://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity?timeout=10s
Content-Type: application/json
Authorization: Basic {{dittodevopsusr}}:{{dittodevopspwd}}

{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": "mqtt-julian2",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://dbt:dbt@mq.jreichwald.de:1883",
            "sources": [{
                "addresses": ["cemos-ditto/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "cemos-ditto/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }]
        }
    }
}

########################################################################################
### Publish something via mqtt #########################################################
### In Topic: cemos-ditto/cemos:optmeasurementdev1 #####################################
########################################################################################

{
  "topic": "cemos/optmeasurementdev1/things/twin/commands/modify",
  "headers": {},
  "path": "/features/coffee-brewer/properties/brewed-coffees",
  "value": {
    "connected": true,
    "brewed-coffees": 60
  }
}

########################################################################################
### Update specific features via HTTP ##################################################
########################################################################################

PATCH {{proto}}://{{hostname}}:{{port}}/api/2/things/cemos:optmeasurementdev1/features/coffee-brewer/properties/brewed-coffees
Content-Type: application/merge-patch+json
Authorization: Basic {{user}}:{{pwd}}

{
"definition":null,
"properties":{
  "connected":true,
  "brewed-coffees":40,
  "bla":40
  }
}


########################################################################################
### Sending Question via HTTP ##########################################################
### In Topic: cemos-ditto/cemos:optmeasurementdev1 #####################################
########################################################################################

POST {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/cemos:optmeasurementdev1/inbox/messages/ask
Content-Type: application/json
Authorization: Basic {{user}}:{{pwd}}

{
"test":"CMD"
}

########################################################################################
### Sending a Command to a specific feature ############################################
### In Topic: cemos-ditto/cemos:optmeasurementdev1 #####################################
########################################################################################

POST {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/cemos:optmeasurementdev1/features/water-tank/inbox/messages/action
Content-Type: application/json
Authorization: Basic {{user}}:{{pwd}}

{
"test":"HEAT"
}

########################################################################################
########################################################################################
### DITTO STUFF ########################################################################
########################################################################################
########################################################################################
########################################################################################
########################################################################################
### DITTO STUFF ########################################################################
########################################################################################
########################################################################################
########################################################################################
########################################################################################
### DITTO STUFF ########################################################################
########################################################################################
########################################################################################

########################################################################################
### Setup policy #######################################################################
########################################################################################

curl -X PUT -u ditto:ditto -H 'Content-Type: application/json' --data '{
  "entries": {
    "DEFAULT": {
      "subjects": {
        "{{ request:subjectId }}": {
          "type": "the creator"
        }
      },
      "resources": {
        "policy:/": {
          "grant": [
            "READ",
            "WRITE"
          ],
          "revoke": []
        },
        "thing:/": {
          "grant": [
            "READ",
            "WRITE"
          ],
          "revoke": []
        },
        "message:/": {
          "grant": [
            "READ",
            "WRITE"
          ],
          "revoke": []
        }
      }
    }
  }
}' http://141.19.44.69:8080/api/2/policies/ns1:policy1

###

curl -X 'PUT' \
  'http://141.19.44.69:8080/api/2/policies/ns1%3Apolicy1' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic ZGl0dG86ZGl0dG8=' \
  -H 'Content-Type: application/json' \
  -d '{
  "entries": {
    "DEFAULT": {
      "subjects": {
        "{{ request:subjectId }}": {
          "type": "the creator"
        }
      },
      "resources": {
        "policy:/": {
          "grant": [
            "READ",
            "WRITE"
          ],
          "revoke": []
        },
        "thing:/": {
          "grant": [
            "READ",
            "WRITE"
          ],
          "revoke": []
        },
        "message:/": {
          "grant": [
            "READ",
            "WRITE"
          ],
          "revoke": []
        }
      }
    }
  }
}'

###

curl -X PUT -H 'accept: application/json' -u ditto:ditto -H 'Content-Type: application/json'  -d '{
  "definition": "com.acme:coffeebrewer:0.1.0",
  "attributes": {
    "manufacturer": "ACME demo corp.",
    "location": "Berlin, main floor",
    "serialno": "42",
    "model": "Speaking coffee machine"
  },
  "features": {
    "coffee-brewer": {
      "definition": [
        "com.acme:coffeebrewer:0.1.0"
      ],
      "properties": {
        "brewed-coffees": 0
      }
    },
    "water-tank": {
      "properties": {
        "configuration": {
          "smartMode": true,
          "brewingTemp": 87,
          "tempToHold": 44,
          "timeoutSeconds": 6000
        },
        "status": {
          "waterAmount": 731,
          "temperature": 44
        }
      }
    }
  }
}' http://141.19.44.61:30080/api/2/things/joel:fancy-car

###

curl -X PUT 'http://141.19.44.61:8080/api/2/policies/my.test:policy' -u 'ditto:ditto' -H 'Content-Type: application/json' -d '{
    "entries": {
        "owner": {
            "subjects": {
                "nginx:ditto": {
                    "type": "nginx basic auth user"
                }
            },
            "resources": {
                "thing:/": {
                    "grant": [
                        "READ","WRITE"
                    ],
                    "revoke": []
                },
                "policy:/": {
                    "grant": [
                        "READ","WRITE"
                    ],
                    "revoke": []
                },
                "message:/": {
                    "grant": [
                        "READ","WRITE"
                    ],
                    "revoke": []
                }
            }
        }
    }
}'

########################################################################################
### Create a twin ######################################################################
########################################################################################

curl -X PUT -u ditto:ditto -H 'Content-Type: application/json' --data '{
   "definition": "digitaltwin:DigitaltwinExample:1.0.0",
   "attributes": {
     "manufacturer": "ACME",
     "VIN": "0815666337"
   },
   "features": {
     "transmission": {
       "properties": {
         "automatic": true, 
         "mode": "eco",
         "cur_speed": 90, 
         "gear": 5
       }
     },
     "environment-scanner": {
       "properties": {
         "temperature": 20.8,
         "humidity": 73,
         "barometricPressure": 970.7,
         "location": {
           "longitude": 47.682170,
           "latitude": 9.386372
         },
         "altitude": 399
       }
     }
   }
 }' http://{{hostname}}:{{dittoport}}/api/2/things/{{org}}:{{honodevice}}


########################################################################################


 curl -u ditto:ditto -X PUT -H 'Content-Type: application/json' -d '{
   "definition": "digitaltwin:DigitaltwinExample:1.0.0",
   "attributes": {
     "manufacturer": "ACME",
     "VIN": "0815666337"
   },
   "features": {
     "transmission": {
       "properties": {
         "automatic": true, 
         "mode": "eco",
         "cur_speed": 90, 
         "gear": 5
       }
     },
     "environment-scanner": {
       "properties": {
         "temperature": 20.8,
         "humidity": 73,
         "barometricPressure": 970.7,
         "location": {
           "longitude": 47.682170,
           "latitude": 9.386372
         },
         "altitude": 399
       }
     }
   }
 }' 'http://141.19.44.69:8080/api/2/things/org.eclipse.ditto:fancy-car'

########################################################################################
### DELETE THE TWIN ####################################################################
########################################################################################

DELETE {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/org.fournier:rf4
Authorization: Basic ditto:ditto

########################################################################################
### Delete all Features #ä##############################################################
########################################################################################

DELETE {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/org.fournier:rf4/features
Authorization: Basic ditto:ditto

########################################################################################
### New Features #ä#####################################################################
########################################################################################

PUT {{proto}}://{{hostname}}:{{dittoport}}/api/2/things/org.fournier:rf4/features
Content-Type: application/json
Authorization: Basic ditto:ditto

{
	"engine": {
		"properties": {
			"manufacturer": [
				"com.rectimo:4AR1200"
			],
			"yearOfManufacturing": 1968,
      "status": {
        "running": {
          "value": true
        },
        "fuelSwitch": {
          "value": true
        },
        "hours": {
          "value": 1804,
        "unit": "h"
        },
        "cylheadtemp": {
          "value": 185,
        "unit": "deg Celsius"
        },
        "oiltemp": {
          "value": 60,
        "unit": "deg Celsius"
        },
        "Tach": {
          "value": 2950,
        "unit": "rpm"
        }
      }
    }
	},
	"airframe": {
		"properties": {
			"configuration": {
				"yearOfManufacturing": 1968,
				"builtNo": 4102,
				"reg": "D-KALC"
			},
			"status": {
				"damaged": false,
				"condition": "fancy"
			}
		}
	},
  "instrumentStatus": {
    "properties": {
      "inFlight": {
        "value": false
      },
      "landingGear": {
        "value": true
      },
      "mainSwitch": {
        "value": true
      },
      "antiCollisionLight": {
        "value": true
      },
      "radio": {
        "value": true,
        "frequency": 118.085,
        "unit": "MHz"
      },
      "qnh": {
        "value": 1013,
        "unit": "hPa"
      },
      "transponder": {
        "value": 7000
      }
    }
  },
  "telemetry": {
    "properties": {
      "altitude": {
        "value": null,
        "unit": "ft"
      },
      "speed": {
        "value": null,
        "unit": "km/h"
      },
      "heading": {
        "value": null,
        "unit": "deg"
      },
      "bank": {
        "value": null,
        "unit": "deg"
      }
    }
  }
}

########################################################################################
### PUBLISH TELEMETRY TO HONO ##########################################################
### Device and Tenant have to be provisioned previously ################################
########################################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}
{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}

####

POST http://141.19.44.65:18443/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}

########################################################################################
### PUBLISH TELEMETRY TO HONO ##########################################################
### Device and Tenant have to be provisioned previously ################################
########################################################################################

### NULL ###############################################################################
### Altitude ###########################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/altitude/value",
  "value": null
}

### Speed ##############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/speed/value",
  "value": null
}

### Heading #############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/heading/value",
  "value": null
}

### Bank ###############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/bank/value",
  "value": null
}

### INFLIGHT ###########################################################################
### Altitude ###########################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic aircraft@joel:{{honodevicepwd}}

{
  "topic": "org.fournier/aircraft/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/altitude/value",
  "value": 3000
}

### Speed ##############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/speed/value",
  "value": 185
}

### Heading #############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/heading/value",
  "value": 245
}

### Bank ###############################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic {{honodevice}}@{{honotenant}}:{{honodevicepwd}}

{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/telemetry/properties/bank/value",
  "value": 15
}



##### MQTT:

{
  "topic": "org.fournier/rf4/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}




########################################################################################
### Create Connection ##################################################################
########################################################################################

curl -i -X POST -u devops:foobar -H 'Content-Type: application/json' --data '{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:createConnection",
    "connection": {
      "id": "hono-connection-for-joel",
      "connectionType": "amqp-10",
      "connectionStatus": "open",
      "uri": "amqp://consumer%40HONO:verysecret@c2e-dispatch-router-ext:15672",
      "failoverEnabled": true,
      "sources": [
        {
          "addresses": [
            "telemetry/joel",
            "event/joel"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "enforcement": {
            "input": "{{ header:device_id }}",
            "filters": [
              "{{ entity:id }}"
            ]
          },
          "headerMapping": {
            "hono-device-id": "{{ header:device_id }}",
            "content-type": "{{ header:content-type }}"
          },
          "replyTarget": {
            "enabled": true,
            "address": "{{ header:reply-to }}",
            "headerMapping": {
              "to": "command/joel/{{ header:hono-device-id }}",
              "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
              "correlation-id": "{{ header:correlation-id }}",
              "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}"
            },
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          },
          "acknowledgementRequests": {
            "includes": [],
            "filter": "fn:filter(header:qos,'"'"'ne'"'"','"'"'0'"'"')"
          }
        },
        {
          "addresses": [
            "command_response/joel/replies"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "headerMapping": {
            "content-type": "{{ header:content-type }}",
            "correlation-id": "{{ header:correlation-id }}",
            "status": "{{ header:status }}"
          },
          "replyTarget": {
            "enabled": false,
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          }
        }
      ],
      "targets": [
        {
          "address": "command/joel",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/live/commands",
            "_/_/things/live/messages"
          ],
          "headerMapping": {
            "to": "command/joel/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}",
            "reply-to": "{{ fn:default('"'"'command_response/joel/replies'"'"') | fn:filter(header:response-required,'"'"'ne'"'"','"'"'false'"'"') }}"
          }
        },
        {
          "address": "command/joel",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/twin/events",
            "_/_/things/live/events"
          ],
          "headerMapping": {
            "to": "command/joel/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}"
          }
        }
      ]
    }
  }
}' http://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity




### DELETE Connection
POST http://devops:foobar@{{hostname}}:38443/devops/piggyback/connectivity?timeout=10 
Content-Type: application/json

{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:deleteConnection",
    "connectionId": "mqtt-example-connection"
  }
}


########################################################################################
### PUBLISH TELEMETRY TO HONO ##########################################################
### Device and Tenant have to be provisioned previously ################################
########################################################################################

POST {{proto}}://{{hostname}}:{{httpadapterport}}/telemetry
Content-Type: application/json
Authorization: Basic aircraft@joel:{{honodevicepwd}}

{
  "topic": "org.fournier/rf4/things/twin/commands/modify",
  "headers": {},
  "path": "/features/engine/properties/status/JoelTemp/value",
  "value": 999
}


###
{
  "topic": "{{org}}/{{honodevice}}/things/twin/commands/modify",
  "headers": {},
  "path": "/features/instrumentStatus/properties/inFlight/value",
  "value": true
}

###################

curl -i -X POST -u devops:foobar -H 'Content-Type: application/json' --data '{
{
      "targetActorSelection": "/system/sharding/connection",
      "headers": {
        "aggregate": false
      },
      "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
          "id": "hono-connection-for-joel",
          "connectionType": "amqp-10",
          "connectionStatus": "open",
          "uri": "amqp://consumer%40HONO:verysecret@c2e-dispatch-router-ext:15672",
          "failoverEnabled": true,
          "sources": [
            {
              "addresses": [
                "telemetry/joel",
                "event/joel"
              ],
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "enforcement": {
                "input": "{{ header:device_id }}",
                "filters": [
                  "{{ entity:id }}"
                ]
              },
              "headerMapping": {
                "hono-device-id": "{{ header:device_id }}",
                "content-type": "{{ header:content-type }}"
              },
              "replyTarget": {
                "enabled": true,
                "address": "{{ header:reply-to }}",
                "headerMapping": {
                  "to": "command/joel/{{ header:hono-device-id }}",
                  "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
                  "correlation-id": "{{ header:correlation-id }}",
                  "content-type": "{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}"
                },
                "expectedResponseTypes": [
                  "response",
                  "error"
                ]
              },
              "acknowledgementRequests": {
                "includes": [],
                "filter": "fn:filter(header:qos,'ne','0')"
              }
            },
            {
              "addresses": [
                "command_response/joel/replies"
              ],
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "headerMapping": {
                "content-type": "{{ header:content-type }}",
                "correlation-id": "{{ header:correlation-id }}",
                "status": "{{ header:status }}"
              },
              "replyTarget": {
                "enabled": false,
                "expectedResponseTypes": [
                  "response",
                  "error"
                ]
              }
            }
          ],
          "targets": [
            {
              "address": "command/joel",
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "topics": [
                "_/_/things/live/commands",
                "_/_/things/live/messages"
              ],
              "headerMapping": {
                "to": "command/joel/{{ thing:id }}",
                "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
                "content-type": "{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}",
                "correlation-id": "{{ header:correlation-id }}",
                "reply-to": "{{ fn:default('command_response/joel/replies') | fn:filter(header:response-required,'ne','false') }}"
              }
            },
            {
              "address": "command/joel",
              "authorizationContext": [
                "pre-authenticated:hono-connection"
              ],
              "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/events"
              ],
              "headerMapping": {
                "to": "command/joel/{{ thing:id }}",
                "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
                "content-type": "{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}",
                "correlation-id": "{{ header:correlation-id }}"
              }
            }
          ]
        }
      }
    }' http://{{hostname}}:{{dittoport}}/devops/piggyback/connectivity


####

POST http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/backlightOn?timeout=0
Content-Type: x-correlation-id: command-and-control
Authorization: Basic ditto:ditto

{
  
}

####

POST http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/backlightOff?timeout=0
Content-Type: x-correlation-id: command-and-control
Authorization: Basic ditto:ditto

{
  
}

####


    curl -i -X POST 'http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/brew?timeout=0' \
     -u ditto:ditto \
     -H 'x-correlation-id: command-and-control' \
     -d '{"targetTemperature":85}'



#####

curl -i -X POST -u ditto:ditto -H 'Content-Type: application/json' -w '\n' --data '{
    "topic": "lehmann/smartDTsensor/things/live/messages/ask",
    "headers": {
        "content-type": "text/plain",
        "correlation-id": "a-unique-string-for-this-message"
    },
    "path": "/inbox/messages/ask",
    "value": "Hey, how are you?"
}' http://141.19.44.65:38443/api/2/things/lehmann:smartDTsensor/inbox/messages/turnoff?timeout=0


####


GET http://jreichwald.de:1880/settings
Authorization: Basic admin:admin1234

{
  
}

#### Test login scheme

GET http://jreichwald.de:1880/auth/login

### login

curl -X POST http://jreichwald.de:1880/auth/token --data 'client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=admin1234'

### login


POST http://twinserver.kve.hs-mannheim.de:18443/auth/token 
Content-Type: application/x-www-form-urlencoded

client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=admin1234


#Content-Type: client_id=node-red-admin&grant_type=password&scope=*&username=admin&password=admin1234

### Token

@NodeRedToken = JUSZpHtMzNnVoa0j9AhlOGwxCEcxx0vFyF/ZunzurXvfsNL9B/Sd9qdY5cz66FreJPei8/f4p2L1CozdD20mLzG7UEGWVvJV/oduvWC7QZBZPRQCvmCW6d+AMQQb/tGoB/wn4E3oaLCNT/tWgN2qi9/igCVGcOs1458IK9hUVJU=

###

GET http://jreichwald.de:1880/settings
Authorization: Bearer {{NodeRedToken}}

####

PUT http://twinserver.kve.hs-mannheim.de:18443/flow/a1cabdb9.dfa9b
Authorization: Bearer {{NodeRedToken}}
Content-Type: application/json
Node-RED-Deployment-Type: reload

{
  "id": "a1cabdb9.dfa9b",
  "label": "Flow 1",
  "nodes": [ 
  {
        "id": "jo9aa7f7.8b39b8",
        "type": "inject",
        "z": "a1cabdb9.dfa9b",
        "repeat": "10",
        "payloadType": "date",
        "x": 130,
        "y": 80,
        "wires": [
            [
                "jof970af.305cf8"
            ]
        ]
    },
    {
        "id": "jof970af.305cf8",
        "type": "http request",
        "z": "a1cabdb9.dfa9b",
        "method": "GET",
        "url": "http://ditto:ditto@twinserver.kve.hs-mannheim.de:38443/api/2/things/selfy:smsensor/features/telemetry/properties/JoelTemp/value",
        "x": 330,
        "y": 80,
        "wires": [
            [
                "jodf7460.349a"
            ]
        ]
    },
    {
        "id": "jodf7460.349a",
        "type": "rbe",
        "z": "a1cabdb9.dfa9b",
        "func": "deadband",
        "gap": "1",
        "inout": "out",
        "property": "payload",
        "x": 530,
        "y": 80
    }
  ]
}


###PUT .../flow/:8f85aefb.b740d8

curl -X POST http://twinserver.kve.hs-mannheim.de:18443/flows -H 'content-type: application/json' -H "Authorization: Bearer {{NodeRedToken}}" -d '{
  "id": "8f85aefb.b740d8",
  "label": "Flow 1",
  "nodes": [ 
  {
        "id": "jo9aa7f7.8b39b8",
        "type": "inject",
        "z": "8f85aefb.b740d8",
        "repeat": "10",
        "payloadType": "date",
        "x": 130,
        "y": 80,
        "wires": [
            [
                "jof970af.305cf8"
            ]
        ]
    },
    {
        "id": "jof970af.305cf8",
        "type": "http request",
        "z": "8f85aefb.b740d8",
        "method": "GET",
        "url": "http://ditto:ditto@twinserver.kve.hs-mannheim.de:38443/api/2/things/selfy:smsensor/features/telemetry/properties/JoelTemp/value",
        "x": 330,
        "y": 80,
        "wires": [
            [
                "jodf7460.349a"
            ]
        ]
    },
    {
        "id": "jodf7460.349a",
        "type": "rbe",
        "z": "8f85aefb.b740d8",
        "func": "deadband",
        "gap": "1",
        "inout": "out",
        "property": "payload",
        "x": 530,
        "y": 80
    }
  ]
}
'


#####################################################################################

curl -X GET http://twinserver.kve.hs-mannheim.de:18443/flows -H 'content-type: application/json' -H "Authorization: Bearer {{NodeRedToken}}"
